[package]
name = "ssclib"
version = "0.2.254"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
somersault-core = { path = "../somersault-core", version = "*" }
anyhow = "1.0.86"
libc = "0.2.79"